config/routes.rb
Rails.application.routes.draw do
  devise_for :users , controllers: {registrations: 'user/registrations'}

  root "home#index"

  put 'like/:id', to: 'likes#like', as: :like
  delete 'unlike/:id', to: 'likes#unlike', as: :unlike

  get 'comment/:post_id', to: 'comments#new', as: :newcomment
  get 'comment/:post_id/:parent_comment_id', to: 'comments#new', as: :newreply
  get 'friends', to: 'friend_requests#index', as: :friends
  put 'friend_request/:receiver_id', to: 'friend_requests#create', as: :sendfriendrequest
  delete 'friend_request/:receiver_id', to: 'friend_requests#destroy', as: :deletefriendrequest
  put 'accept_request/:sender_id/:accept', to: 'friend_requests#update', as: :acceptfriendrequest

  resources :comments
  resources :posts
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/">Facebook</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "home", root_path, class:"nav-link"%>
      </li>
      <li class="nav-item active">
        <%= link_to "posts", posts_path, class:"nav-link"%>
      </li>
      <li class="nav-item active">
        <%= link_to "friends", friends_path, class:"nav-link"%>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
        <%= link_to "edit profile", edit_user_registration_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
        <%= link_to "Sign out", destroy_user_session_path, data: {turbo_method: :delete}, class:"nav-link"%>
        </li>
    <% else %>
      <li class="nav-item">
      <%= link_to "Signin", new_user_session_path, class:"nav-link"%>
      </li>
      <li class="nav-item">
      <%= link_to "Signup", new_user_registration_path, class:"nav-link"%>
      </li>
      <%end%>
    </ul>
    <div class="form-inline my-2 my-lg-0">
    <%if current_user%>
      <span class="text-white"><%= current_user.username%></span>
      <%end%>
      <%# if current_user %>
       <%# button_to "Logout #{current_user.name}", logout_path, method: :delete, class: "btn btn-outline-success my-2 my-sm-0" %>
      <%# else %>
       <%# button_to "Login", login_path, method: :get, class: "btn btn-outline-success my-2 my-sm-0" %>
      <%# end %>
    </div>
    
  </div>
</nav>  