config/routes.rb
Rails.application.routes.draw do
  devise_for :users , controllers: {registrations: 'user/registrations'}

  root "home#index"

  put 'like/:id', to: 'likes#like', as: :like
  delete 'unlike/:id', to: 'likes#unlike', as: :unlike

  get 'comment/:post_id', to: 'comments#new', as: :newcomment
  get 'comment/:post_id/:parent_comment_id', to: 'comments#new', as: :newreply
  get 'friends', to: 'friend_requests#index', as: :friends
  put 'friend_request/:receiver_id', to: 'friend_requests#create', as: :sendfriendrequest
  delete 'friend_request/:receiver_id', to: 'friend_requests#destroy', as: :deletefriendrequest
  put 'accept_request/:sender_id/:accept', to: 'friend_requests#update', as: :acceptfriendrequest

  resources :comments
  resources :posts
end

app/models/friend_request.rb
class FriendRequest < ApplicationRecord
    belongs_to :sender, class_name: 'User'
    belongs_to :receiver, class_name: 'User'

    validates :sender_id, uniqueness: { scope: :receiver_id }
end
 

app/controllers/friend_requests_controller.rb
class FriendRequestsController < ApplicationController
  before_action :require_login, only: %i[ index create edit update destroy ]
  before_action :require_owner, only: %i[ destroy ]


  def index
    @users = User.where.not(id: current_user.id)
    @sent_friend_requestsids = current_user.sent_friend_requests.where(accepted:false).pluck(:receiver_id)
    @received_friend_requestsids = current_user.received_friend_requests.where(accepted:false).pluck(:sender_id)
    @friends = current_user.sent_friend_requests.where(accepted: true).map(&:receiver) +
                current_user.received_friend_requests.where(accepted: true).map(&:sender)

  end
  # POST Friend Request
  def create
    @friend_request= FriendRequest.new(accepted: false, sender_id: current_user.id, receiver_id: params[:receiver_id])    
    if @friend_request.save
      redirect_to friends_path, notice: 'Friend Request sent!'
    else
      redirect_to friends_path, alert: @friend_request.errors.full_messages.join(', ')
    end
    
  end

  # PATCH/PUT /friend request Accept
  def update
    @friend_request = FriendRequest.find_by(receiver_id:current_user.id ,sender_id:params[:sender_id]);
    @friend_request.accepted = params[:accept]
    if @friend_request.save
      redirect_to friends_path, notice: 'Friend Request accepted!'
    else
      redirect_to friends_path, alert: @friend_request.errors.full_messages.join(', ')
    end

  end

  # DELETE unfriend, Friend Request deleted
  def destroy
    if @friend_request.destroy
      redirect_to friends_path, notice: 'Friend Request deleted!'
    else
      redirect_to friends_path, alert: @friend_request.errors.full_messages.join(', ')
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def require_login
      unless current_user
        redirect_to user_session_path, alert: 'Please log in.'
      end
    end

    def require_owner
      @friend_request = FriendRequest.find_by(receiver_id:params[:receiver_id],sender_id:current_user.id);
      unless @friend_request
        redirect_to user_session_path, alert: 'Please log in.'
      end
    end
end

app/views/friend_requests/_friend.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.username %>
  </p>

</div>

app/views/friend_requests/index.html.erb
<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%# render friend %>
    <%=user.username%>
    <% if(@sent_friend_requestsids.include?(user.id)) %>
      <p>
        <%= button_to "UnSend Freind Request", deletefriendrequest_path(user), method: :delete, remote: true%>
      </p>
    <% elsif(@received_friend_requestsids.include?(user.id)) %>
      <P>
        <%= button_to "Accept Freind Request", acceptfriendrequest_path(user,accept:true), method: :put, remote: true%>
      </p>
    <% elsif(@friends.pluck(:id).include?(user.id)) %>
      <p> 
      <%= button_to "Unfriend", deletefriendrequest_path(user), method: :delete, remote: true%>
      </p>
    <% elsif(!@sent_friend_requestsids.include?(user.id) && !@received_friend_requestsids.include?(user.id)) %>
      <p> 
        <%= button_to "Send Freind Request", sendfriendrequest_path(user), method: :put, remote: true%>
      </p>
    <%end%>
    
    
    
    
  <% end %>
</div>