config/routes.rb
Rails.application.routes.draw do
  devise_for :users , controllers: {registrations: 'user/registrations'}

  root "home#index"

  put 'like/:id', to: 'likes#like', as: :like
  delete 'unlike/:id', to: 'likes#unlike', as: :unlike

  get 'comment/:post_id', to: 'comments#new', as: :newcomment
  get 'comment/:post_id/:parent_comment_id', to: 'comments#new', as: :newreply
  get 'friends', to: 'friend_requests#index', as: :friends
  put 'friend_request/:receiver_id', to: 'friend_requests#create', as: :sendfriendrequest
  delete 'friend_request/:receiver_id', to: 'friend_requests#destroy', as: :deletefriendrequest
  put 'accept_request/:sender_id/:accept', to: 'friend_requests#update', as: :acceptfriendrequest

  resources :comments
  resources :posts
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :comments, dependent: :destroy
    has_many :likes, dependent: :destroy

    validates :title, presence: true
    validates :content, presence: true
    def self.ransackable_attributes(auth_object = nil)
        ["content", "created_at", "id", "title", "updated_at", "user_id"]
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :require_login, only: %i[ new create edit update destroy]
  before_action :require_owner, only: %i[  edit update destroy]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
    @q = Post.ransack(params[:q])
    @posts = @q.result
  end

  # GET /posts/1 or /posts/1.json
  def show
    @likes = @post.likes.pluck(:user_id)
    @comments = @post.comments.includes(:replies) 
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
    def require_login
      unless current_user
        redirect_to user_session_path, alert: 'Please log in.'
      end
    end
    def require_owner
      unless @post.user == current_user
        redirect_to user_session_path, alert: 'Please log in as post owner.'
      end
    end
end

app/helpers/posts_helper.rb
module PostsHelper
    def render_comments(comments)
        comments.map do |comment|
          unless comment.parent_comment
            render_comment(comment) +
              render_child_comments(comment.replies)
          end
        end.join.html_safe
      end
    
      def render_comment(comment)
        content_tag(:div) do
          concat(content_tag(:strong, comment.user.username))
          concat(": ")
          concat(comment.content)
          concat(tag(:br))
          concat(link_to("Show this comment", comment))
          concat(tag(:br))
          concat(link_to("Reply to this comment", newreply_path(@post, comment)))
          concat(tag(:br))
        end
      end
    
      def render_child_comments(replies)
        replies.map do |reply|
          content_tag(:div, class: "ml-4") do
            render_comment(reply) +
              render_child_comments(reply.replies)
          end
        end.join.html_safe
      end
end

app/views/posts/_comment.html.erb
<!-- comments/_comment.html.erb -->

<%= comment.user.name %>: <%= comment.content %><br>
<p>
  <%= link_to "Show this comment", comment %><br>
  <%= link_to "Reply to this comment", newreply_path(@post, comment) %>
</p>

<% comment.replies.each do |reply| %>
  <div style="margin-left: 20px;">
    <%= render partial: 'comment', locals: { comment: reply } %>
  </div>
<% end %>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
<div class="jumbotron">
  <h1 class="display-4"> <%= post.title %></h1>
  <p class="lead"><%= post.content %></p>
  <p> by : <%= post.user.username%></p>
  <hr class="my-4">
  
  

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Posts</h1>
<%= link_to "New post", new_post_path %>
<%= search_form_for @q, remote: true do |f| %>
  <%= f.label :content_cont, 'Content' %>
  <%= f.search_field :content_cont %>
  <%= f.submit %>
<% end %>
<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
        <p class="lead">
        <%= button_to "show this post", post, class:"btn btn-primary", method: :get %>
      </p>
    </div>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/posts/show.html.erb
<%= render @post %>
  likes: <%=@likes.size%></br>
  comments: <%=@comments.size%>
  <p class="lead">
  <% if(current_user && @likes.include?(current_user.id)) %>
  <%= link_to "unlike this post", unlike_path(@post), class:"btn btn-danger", data: { "turbo-method": :delete }%>
  <% elsif current_user%>
  <%= link_to "like this post", like_path(@post), class:"btn btn-success", data: { "turbo-method": :put }%>
  <% else %>
  <%= link_to "like this post", new_user_session_path, class: "btn btn-success" %>
  <%end%>
  <%= link_to "comment this post", newcomment_path(@post), class:"btn btn-success"%>
  </br>

  <%= link_to "Back to posts", posts_path ,class:"btn btn-primary mt-2"%></br>
  <% if current_user && @post.user_id==current_user.id%>
  <%= link_to "Edit this post", edit_post_path(@post), class:"btn btn-secondary mt-2"%>
  <%= link_to "Destroy this post", @post, method: :delete, class:"btn btn-danger mt-2" ,data: { "turbo-method": :delete }%>
  <%end%>
  </p>
  <h2>Comments:</h1>
  <div id="comments" class="mt-2">
    <%= render_comments(@comments) %>
  </div>
</div>




<% def render_comments(comments) %>
  <% comments.each do |comment| %>
    <% unless comment.parent_comment %>
      <div>
        <strong><%= comment.user.name %></strong>: <%= comment.content %><br>
        <p>
          <%= link_to "Show this comment", comment %><br>
          <%= link_to "Reply to this comment", newreply_path(@post, comment) %>
        </p>
        <%# render_child_comments(comment.replies) %>
      </div>
    <% end %>
  <% end %>
<% end %>

<% def render_child_comments(replies) %>
  <% replies.each do |reply| %>
    <div style="margin-left: 20px;">
      <strong><%= reply.user.name %></strong>: <%= reply.content %><br>
      <p>
        <%= link_to "Show this comment", reply %><br>
        <%= link_to "Reply to this comment", newreply_path(@post, reply) %>
      </p>
      <%= render_child_comments(reply.replies) %>
    </div>
  <% end %>
<% end %>

</div>